name: Scheduled HotDeal Crawler

on:
#  schedule:
#    # 매 시간의 0분, 30분마다 실행 (한국 시간 기준 매시 정각 및 30분)
#    - cron: '0,30 * * * *'
  workflow_dispatch: # 수동 실행 버튼 활성화

jobs:
  crawl-and-insert:
    runs-on: ubuntu-latest

    steps:
      - name: 커밋된 소스코드 체크아웃
        uses: actions/checkout@v4

      - name: Node.js 환경 설정
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 패키지 설치
        working-directory: ./crawler
        run: npm install

      - name: 크롤러 실행
        working-directory: ./crawler
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: node src/presentation/cli/index.js
